version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=secret_santa
    ports:
      - "5432:5432"
    volumes:
      - /Users/yves/dev/database/postgresql/data:/var/lib/postgresql/data
volumes:
  pgdata: